sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "0.12"
before_install:
  - "npm i -g spacejam"
  - "curl https://install.meteor.com | /bin/sh"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "npm prune"
script:
  - "npm run test"
  - "npm run test:meteor"
after_success:
  - "npm run coverage:coveralls"
#
#deploy:
#  provider: npm
#  auth_key: "pbastowski-top-secret-api-key"
#  on:
#    tags: true
#
